### ISSUE TITLE
Invite - ERROR: relation "group_users" does not exist

### ISSUE THREAD

**Issue by dennis-ledergerber** [ma1uta/ma1sd#115]
After the upgrade from Matrix-Synapse v1.61.0 -> v1.64.0, the invitation of external users is not working anymore. 
Inside the GUI it shows "Unknown server error" and does not send any message. The ma1sd log shows the following error. Is it possible that this feature isnt working anymore because the Communities (Groups) are deprecated since Matrix-Synapse v1.62.0? Is there a workaround. Or any other way to restrict the users which can invite?

Aug 12 14:07:09 699matrix ma1sd[2147]: [XNIO-1 task-2] ERROR io.kamax.mxisd.http.undertow.handler.SaneHandler - Unknown error when handling http://matrix.xxx.xx/_matrix/client/r0/rooms/!qeXCeEWzgrxCsYjEMr%3Ama
Aug 12 14:07:09 699matrix ma1sd[2147]: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: relation "group_users" does not exist
Aug 12 14:07:09 699matrix ma1sd[2147]:   Position: 32
Aug 12 14:07:09 699matrix ma1sd[2147]:         at io.kamax.mxisd.backend.sql.SqlProfileProvider.getRoles(SqlProfileProvider.java:128)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at io.kamax.mxisd.profile.ProfileManager.lambda$getRoles$3(ProfileManager.java:85)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at io.kamax.mxisd.profile.ProfileManager.getList(ProfileManager.java:65)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at io.kamax.mxisd.profile.ProfileManager.getRoles(ProfileManager.java:85)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at io.kamax.mxisd.invitation.InvitationManager.canInvite(InvitationManager.java:250)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at io.kamax.mxisd.http.undertow.handler.invite.v1.RoomInviteHandler.handleRequest(RoomInviteHandler.java:95)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at io.kamax.mxisd.http.undertow.handler.SaneHandler.handleRequest(SaneHandler.java:71)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at java.lang.Thread.run(Thread.java:748)
Aug 12 14:07:09 699matrix ma1sd[2147]: Caused by: org.postgresql.util.PSQLException: ERROR: relation "group_users" does not exist
Aug 12 14:07:09 699matrix ma1sd[2147]:   Position: 32
Aug 12 14:07:09 699matrix ma1sd[2147]:         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at org.postgresql.jdbc.PgPreparedStatement.getParameterMetaData(PgPreparedStatement.java:1666)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.getParameterMetaData(NewProxyPreparedStatement.java:1159)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at io.kamax.mxisd.backend.sql.SqlProfileProvider.setParameters(SqlProfileProvider.java:54)
Aug 12 14:07:09 699matrix ma1sd[2147]:         at io.kamax.mxisd.backend.sql.SqlProfileProvider.getRoles(SqlProfileProvider.java:113)
Aug 12 14:07:09 699matrix ma1sd[2147]:         ... 20 more
Aug 12 14:07:09 699matrix ma1sd[2147]: [XNIO-1 task-2] INFO io.kamax.mxisd.http.undertow.handler.BasicHttpHandler - Request POST http://matrix.xxx.xx/_matrix/client/r0/rooms/!qeXCeEWzgrxCsYjEMr%3Amatrix.xxx.xx
Aug 12 14:07:09 699matrix ma1sd[2147]:   Position: 32

Thanks for your help. 

Kind regards
Dennis

**Comment by janonym1** [comment]
Communities was actually already removed with 1.61: https://github.com/matrix-org/synapse/blob/develop/docs/upgrade.md#removal-of-deprecated-communitygroups

I maybe mistaken but I think, the communities (and spaces now) features was never really completely usable with ma1sd in the first place. How did you configure external invite and the registration (homeserver and ma1sd config)? I think open registration was disabled because of spam a longer time ago with 1.56: https://github.com/matrix-org/synapse/blob/develop/docs/upgrade.md#open-registration-without-verification-is-now-disabled-by-default

Did you manage the external registration with an email? As far as I know, the email delegation verification is deprecated and now managed by synapse itself and not the identity server (ma1sd) anymore:
https://matrix-org.github.io/synapse/v1.66/upgrade.html#deprecation-of-the-ability-to-delegate-e-mail-verification-to-identity-servers

It could also have to do with the old V1 version still used by ma1sd: https://github.com/matrix-org/sydent/issues/338
