### ISSUE TITLE
Migrating from mxisd to ma1sd

### ISSUE THREAD

**Issue by the-moog** [ma1uta/ma1sd#15]
Not really an issue, but to avoid downtime I'm just checking if the process is seamless.

Now it's had a while to stabilise I want to remove mxisd and migrate to ma1sd.

Is there a document that describes the process, indicating any changes required?
Are there any features removed/changed that may trip me up?
Any other advice?

I'm running latest Debian package for matrix-synapse 1.8.0.
mxisd is from 1.4.3-2 it's been running fine for ages.

**Comment by ma1uta** [comment]
Hello. Yes, there is a document for migration: https://github.com/ma1uta/ma1sd/blob/master/docs/migration-from-mxisd.md
I try to make ma1sd 2.x.x compatibility with mxisd, it uses the same configuration.
Of course I strongly suggest to create backup before upgrading.

There is only one breaking change: ma1sd replaced the MSC1915 (unbind) implementation, it don't show message about fraudulent unbind requests, so people can configure the ma1sd behaviour for unbind, see https://github.com/ma1uta/ma1sd/blob/master/docs/threepids/session/session.md#usage

**Comment by the-moog** [comment]
Assuming your note about MSC1915 is only informative and needs no action from myself it seems the migraiton went without any fuss.
