### ISSUE TITLE
Incorrect doc and or code for sql backend

### ISSUE THREAD

**Issue by the-moog** [ma1uta/ma1sd#22]
https://github.com/ma1uta/ma1sd/blob/master/docs/stores/sql.md
States that sql:identity:type should be 'localpart' or 'mxid'
But code in line 82 of 
src/main/java/io/kamax/mxisd/backend/sql/SqlThreePidProvider.java states
says only 'uid' or 'mxid' is accepted
Which is correct?

**Comment by ma1uta** [comment]
Thanks for the issue.
