### ISSUE TITLE
Log in with ma1sd in other apps?

### ISSUE THREAD

**Issue by clemsos** [ma1uta/ma1sd#35]
Hello, 

I would like to know if it will be possible to use ma1sd to log to other apps than matrix?   
I have in mind something like OAuth2. Not sure if this a realistic request, if there is any existing implementation or pointers about how to implement this?

Many thanks for the work!

**Comment by ma1uta** [comment]
No. You can look at the https://www.keycloak.org/ or https://www.apereo.org/projects/cas
