### ISSUE TITLE
IPV4

### ISSUE THREAD

**Issue by root562** [ma1uta/ma1sd#36]
I just installed, configured and run ma1sd. I notice it uses port 8090 on IPV6. How do I change it to IPV4?

**Comment by ma1uta** [comment]
ma1sd binds to all available interfaces so it also uses http://127.0.0.1:8090.
If ma1sd doesn't bind to the 127.0.0.1 please reopen the issue.

**Comment by AlphaDE** [comment]
Same issue here, was solved by adding 

`RestrictAddressFamilies=AF_INET AF_UNIX AF_NETLINK`

in the `[Service]` of the system unit.
