### ISSUE TITLE
Doesn't seem to work with recent versions of riot

### ISSUE THREAD

**Issue by prurigro** [ma1uta/ma1sd#37]
I was able to connect fine with desktop (though never with the android client) when I first hooked ma1sd up, but at one point riot upgraded and since then if I or anyone on my server tries to connect it says "Terms of service not accepted or the identity server is invalid".

This has been the case for a while but I figured I'd try again after seeing the latest commit and tested with git master, unfortunately the problem is still there though.

I'm not really sure how to debug but would be happy to try if someone could point me in the right direction-- the server shows a successful launch but no logging output for connection attempts.

Thanks!

**Comment by root562** [comment]
I am new to Matrix. I just tried installing and configuring. I got to your stage. Same error. Try this, go to ma1sd.yaml file, set both v1 and v2 to true, restart ma1sd.

**Comment by ma1uta** [comment]
Recent versions of Riot required enable V2 API (MSC2140) which disabled by default in the ma1sd: https://github.com/ma1uta/ma1sd/blob/master/docs/MSC2140_MSC2134.md
You can enable it to fix this issue.
Also v2 API will be enabled in the next release.
