### ISSUE TITLE
Identity server has no terms of service

### ISSUE THREAD

**Issue by root562** [ma1uta/ma1sd#39]
I just installed ma1sd on my homeserver. When I try adding identity server on Riot web app. A warning appeared "Identity server has no terms of service." It can add after clicking continue. What is the reason for this warning?

**Comment by eMPee584** [comment]
You have to add them to your ma1sd config.. by default, they are empty..
https://github.com/ma1uta/ma1sd/blob/master/ma1sd.example.yaml#L183

**Comment by ma1uta** [comment]
RiotX require the v2 API should be enabled. Just enable v2 in the ma1sd config: https://github.com/ma1uta/ma1sd/blob/master/docs/MSC2140_MSC2134.md
