### ISSUE TITLE
Email address does not show

### ISSUE THREAD

**Issue by rootuser** [ma1uta/ma1sd#43]
Hello! 

Thank you very much for this plugin. It seems to be exactly what I need, though I have barely tested it so far.

Today I installed ma1sd using the matrix-docker-ansible-deploy. I configured it to connect to to our LDAP Server and now one can login to Riot using LDAP user profiles. That is cool already.

I was not able though to have Riot show the email address of a user in the general settings. The configuration I used should be correct (as far as I've taken from the docs); even the default config of the ansible script should normally work itself (but it doesn't).
This is what I have in the configuration file:

> matrix_synapse_registrations_require_3pid: ["email"]
matrix_ma1sd_matrixorg_forwarding_enabled: false

> matrix_ma1sd_threepid_medium_email_identity_from: "matrix@{{ matrix_domain }}"
matrix_ma1sd_threepid_medium_email_connectors_smtp_host: "mail.mymailserver.de"
matrix_ma1sd_threepid_medium_email_connectors_smtp_port: 587
matrix_ma1sd_threepid_medium_email_connectors_smtp_tls: 1
matrix_ma1sd_threepid_medium_email_connectors_smtp_login: "matrix@myhomedomain.de"
matrix_ma1sd_threepid_medium_email_connectors_smtp_password: "mysecretpassword"

> matrix_ma1sd_verbose_logging: true

> matrix_synapse_ext_password_provider_rest_auth_enabled: true
matrix_synapse_ext_password_provider_rest_auth_endpoint: "http://matrix-ma1sd:8090"

> matrix_ma1sd_configuration_extension_yaml: |
  ldap:
    enabled: true
    connection:
      host: 'ucs.myldapserver.com'
      tls: true
      port: 636
      baseDNs:
        - 'cn=users,dc=myhomedomain,dc=local'
      bindDn: 'uid=ldapuser,cn=users,dc=myhomedomain,dc=local'
      bindPassword: 'myverysecretpassword'
    attribute:
      name: 'displayName'
      uid:
        type: 'uid'
        value: 'uid'
      threepid:
        email:
          - 'email'
          - 'mailPrimaryAddress'

(indentation is correct, though not correctly shown here)

The search for email addresses in the 'start chat' window is working though. It's only just strange that this search always creates log entries of the type
> Mai 12 22:28:57 matrix matrix-ma1sd[26511]: [XNIO-1 task-2] INFO io.kamax.mxisd.directory.DirectoryManager - Threepid: found 1 match(es) for 'test@'
Mai 12 22:28:57 matrix matrix-ma1sd[26511]: [XNIO-1 task-2] INFO io.kamax.mxisd.directory.DirectoryManager - Threepid: found 0 match(es) for 'test@'

So immediately following each line with one or more matches there is a line with no matches for the same search term.

What am I missing? Thanks for any hint you may have!
Best, Tom

**Comment by Metzlmane** [comment]
I can confirm this.
After the migrating via the ansible-docker script from mxisd to this version mail and telephone number are not shown anymore

```
ldap:
    attribute:
        name: cn
        threepid:
            email:
            - mail
            msisdn:
            - telephoneNumber
            name:
            - cn
        uid:
            type: uid
            value: uid
```
I can still search for email addresses and phone numbers.

**Comment by rootuser** [comment]
Hello, 
I have additional information concerning this issue.

In the meantime I have tried out the Synapse admin API [https://github.com/matrix-org/synapse/tree/master/docs/admin_api](url)

When creating a user via this API, you can also provide 3PIDs, which I tried. 
In my test I got a valid user creation response, confirming the email address I provided. But when I logged in as that test user, the email address was not shown in the user settings either.

When I tried to enter the same email address in the user settings, I was told that it was used already.

So it seems to me we have a Riot (or perhaps Synapse API) error rather than a ma1sd issue.

Best, Tom

**Comment by rootuser** [comment]
Update: I did indeed find a relevant bug in the Riot Web issues:
[https://github.com/vector-im/riot-web/issues/13033](url)

So I guess this issue can be closed. 
Sorry for bugging you!
