### ISSUE TITLE
ldap: sanitation for attributes

### ISSUE THREAD

**Issue by mk-hs** [ma1uta/ma1sd#63]
When SSO is configured for matrix, usernames are properly converted to lowercase upon login. `uid: usER --> @user:domain.com`
This is necessary since matrix only allows lowercase in usernames.

When trying to map an ldap directory to user with ma1sd, no such sanitation happens. If the uid for a specific users includes uppercase letters, the resulting matrix id is unusable. `uids: usER --> @usER@domain.com`
Matrix treats `@usER:domain.com` and `@user:domain.com` as different users.

I was unable to find any documentation on it, is it possible to sanitize ldap attributes like this?

**Comment by q-wertz** [comment]
having the same problem... 
would be a very important feature, as one can not always control the LDAP content

**Comment by q-wertz** [comment]
I tried to find the relevant code and tried a solution.
As I am not very experienced with java and especially the ma1sd code I don't really know if this if correct.
Should I just open a pull request and then you tell me how to do better?
