### ISSUE TITLE
Update instructions to get rid of depreciated trusted_third_party_id_servers value

### ISSUE THREAD

**Issue by q-wertz** [ma1uta/ma1sd#68]
In some of the instructions (e.g. https://github.com/ma1uta/ma1sd/blob/master/docs/getting-started.md) there are still some places where the user is told to set the variable `trusted_third_party_id_servers` in `homeserver.yaml`.
This variable is depreciated with synapse v1.4.0 (see [Changelog](https://github.com/matrix-org/synapse/blob/782dd72037cf71fb3f9e4922b07c56df2f59de75/CHANGES.md#deprecations-and-removals) and [PR \#5875](https://github.com/matrix-org/synapse/pull/5875)) and the instructions should be updated.

**Comment by ma1uta** [comment]
Thanks.

**Comment by q-wertz** [comment]
Closed with https://github.com/ma1uta/ma1sd/commit/90b2b5301c34168346fdc5e7eccc09d6958e999f
