### ISSUE TITLE
Questions with usage of matrix-docker-ansible-deploy

### ISSUE THREAD

**Issue by CodingAnonymous** [ma1uta/ma1sd#72]
I'm using `matrix-docker-ansible-deploy` and have these configurations:
```
matrix_synapse_enable_registration: true
matrix_synapse_registrations_require_3pid:
  - email
```
1. I want to use `ma1sd` as an identity store. Are the settings above the correct settings? Do I have to use `matrix_ma1sd_configuration_extension_yaml` or `matrix_nginx_proxy_proxy_matrix_3pid_registration_`?
2. What are the best settings for me use case?
3. On `element-web` in the settings of the user I don't see the email I registered my account with and can't add this email because `it is already in use`. What am I doing wrong?

**Comment by ma1uta** [comment]
1. Settings https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/group_vars/matrix_servers#L729 will configure ma1sd which uses synapse database only. If you want add some extra settings (i. e. LDAP integration) you can do it via `matrix_ma1sd_configuration_extension_yaml`. It depend on your requirements.

2. It depend on your requirements. Ma1sd can lookup users by LDAP server, another RDBMS instance, ... Also ma1sd with https://github.com/ma1uta/matrix-synapse-rest-password-provider can register and authenticate new user from LDAP for example.

3. For `element-web` you should setup `m.identity_server` as your ma1sd instance. Also this email can be registered to another user, you can check it in the `user_threepid_id_server` table
