### ISSUE TITLE
Invitation - LDAP 

### ISSUE THREAD

**Issue by dennis-ledergerber** [ma1uta/ma1sd#8]
Hi 
I'm testing matrix-synapse with ma1sd and active directory integration. I would like to use the "Invites-Only" feature to give a group of users permission to invite external contacts so they can register on our matrix server. 
How do I need to setup ma1sd to achieve this? How can I set the roles? Is possible to connect AD groups with roles?
Thanks for your help
dennis

**Comment by MarisOnPremises** [comment]
Why did You close this issue? I am also intereted in AD group solution. I would like to use AD groups:
1. create room by AD group with all group users as room members;
2. add users to room by AD group names

In my opinion, groups are the main active directory feature. In our company these groups has been used for almost all internal applications acces rights.

**Comment by dennis-ledergerber** [comment]
I've closed the issue, because I could solve the main problem with communities. But I will reopen a request regarding the AD sync with groups.

**Comment by Dreadlock77** [comment]
Hi guys
How did you managed to set up LDAP inside ma1sd.yaml to authenticate against AD?
I've read all the guide, followed step by step, but when I log in into my selfhosted element, no user matches
