### ISSUE TITLE
No allow register user [request failed: CORS request rejected /_matrix/client/r0/register/email/requestToken ] 

### ISSUE THREAD

**Issue by AnonymousWebHacker** [ma1uta/ma1sd#96]
Steps:
### Matrix-synapse
`homeserver.yaml`, is configured with register enabled and the mail server conf

### ma1sd
1 - I installed ma1sd from .deb (Ubuntu Focal )
   - Conf ma1sd on `/etc/ma1sd/ma1sd.yam`  to used BD on sqlite , mail server conf and matrix server hostname
   ```
   storage:
# backend: sqlite # or postgresql
  provider:
    sqlite:
      database: '/var/lib/ma1sd/store.db'
```

   - Nginx vhost called vector-im.domain.com
   
   ```    location /_matrix/identity {
        proxy_pass http://localhost:8090/_matrix/identity;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
    
    ```
    and mas1sd service is running right
    
    ### Element-web
    on `config.json ` edit
    
    ```
            "m.identity_server": {
            "base_url": "https://vector-im.domain.com"
        }
```
element seems that it connected well to ma1sd because it did not give errors that it had not connected to the identity server.

but

When I try to register a user with email, I get an error 
```
request failed: CORS request rejected: https://matrix.domain.com/_matrix/client/r0/register/email/requestToken
```
![Captura de pantalla de 2021-06-14 00-44-40](https://user-images.githubusercontent.com/43164089/121840204-c74a3280-cca9-11eb-8e83-971fbe1afd2e.png)

**Comment by AnonymousWebHacker** [comment]
fixed

**Comment by psychofaktory** [comment]
@AnonymousWebHacker 
How was this fixed?

Got the error "request failed: CORS request rejected: https://<mymatrixdomain.com>/_matrix/client/r0/account/3pid/email/requestToken" while trying to add an E-Mail-Adress.

**Comment by AnonymousWebHacker** [comment]
> @AnonymousWebHacker How was this fixed?
> 
> Got the error "request failed: CORS request rejected: https://<mymatrixdomain.com>/_matrix/client/r0/account/3pid/email/requestToken" while trying to add an E-Mail-Adress.

I barely remember, it was a long time ago.

I think you have to ensure the correct mail syntax in the homeserver.yaml
 and have a configuration in the _/matrix/client file
